[versions]
activity = "1.8.2"
appcompat = "1.6.1"
material = "1.11.0"
constraintlayout = "2.1.4"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activity" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
